### ISSUE TITLE
[TODO] Tree searcher

### ISSUE THREAD

**Issue by mrbermell** [mrbermell/ffai#42]
**SearchTree**
- [x] Function which is called on each new Node

. 

**Searchers**
- [ ] only consider nodes which have unexplored actions 
- [ ] MCTS with Upper Confidence Bound 
- [ ] Online Evolution (bunch all action related to one player together)  

**Tree Evaluators**
- [ ] Expect min/max
- [ ] MCTS nodes visited (AlphaGo) 

.

**Expand function for procs**
- [x] Block 
- [x] Knockdown (armor, injury) 
- [x] Handoff
- [ ] Throw In
- [x] Catch 

.

**Action filter**
- [ ] force end player turn after first move action if MoveAction. (Unless carrying ball) 
- [ ] (only pass to players, not empty square)
- [ ] only allow Block/Handoff action when started blitz/handoff(if carrying ball) 
- [ ] (force pass after first move. ) 
- [ ] Force ball pickup if handoff/(pass) action without carrying ball 
- [ ] Don't allow end player turn after just started action (probably just check player.state.moves to determine) unless only action 
- [ ] kick middle 

**Reward** 
- [x] TD: 1.0 reward per td. 
- [x] TV on pitch: normalized to 11 vs. 0 becomes 2.0 reward. one removal = 0.2
- [x] carry ball: +/- 0.2
- [x] mark ball (one player counts): +/- 0.01   
- [x] ball position: 0.001 per square -> 10 sq=0.01 

**Nice before generating data** 
- [ ] Academy agent evaluation
